<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import pandas as pd
import numpy as np

In [2]:
avg_drivingdistance = pd.read_html('https://www.pgatour.com/content/pgatour/stats/stat.101.y2019.eon.t014.html')[1]
drivingaccuracy = pd.read_html('https://www.pgatour.com/content/pgatour/stats/stat.102.y2019.eon.t014.html')[1]
gir = pd.read_html('https://www.pgatour.com/content/pgatour/stats/stat.103.y2019.eon.t014.html')[1]
scrambling = pd.read_html('https://www.pgatour.com/content/pgatour/stats/stat.130.y2019.eon.t014.html')[1]
sandsaves = pd.read_html('https://www.pgatour.com/content/pgatour/stats/stat.111.y2019.eon.t014.html')[1]
putting_avg = pd.read_html('https://www.pgatour.com/content/pgatour/stats/stat.104.y2019.eon.t014.html')[1]

In [3]:
df1 = avg_drivingdistance[['PLAYER NAME','AVG.']].rename(columns={'AVG.': 'avg_driv_dist'}).set_index('PLAYER NAME')

In [4]:
df2 = drivingaccuracy[['PLAYER NAME','%']].rename(columns={'%': 'driv_acc%'}).set_index('PLAYER NAME')

In [5]:
df3 = gir[['PLAYER NAME','%']].rename(columns={'%': 'gir%'}).set_index('PLAYER NAME')

In [6]:
df4 = scrambling[['PLAYER NAME','%']].rename(columns={'%': 'scrambling%'}).set_index('PLAYER NAME')

In [7]:
df5 = sandsaves[['PLAYER NAME','%']].rename(columns={'%': 'sandsaves'}).set_index('PLAYER NAME')

In [8]:
df6 = putting_avg[['PLAYER NAME','AVG']].rename(columns={'AVG': 'putting_avg'}).set_index('PLAYER NAME')

In [9]:
leaderboard = pd.read_html('https://www.espn.com/golf/leaderboard?tournamentId=401056527')[0]
leaderboard['PLAYER'] = leaderboard['PLAYER'].str.replace(r"\(.*\)","").str.replace(r'[^a-zA-Z .]+', '').str.strip()
leaderboard = leaderboard[['PLAYER','TO PAR']].rename(columns={'TO PAR': 'score','PLAYER': 'PLAYER NAME'}).set_index('PLAYER NAME')
leaderboard

                    score
PLAYER NAME
Tiger Woods           -13
Dustin Johnson        -12
Xander Schauffele     -12
Brooks Koepka         -12
Jason Day             -11
...                   ...
Paul Casey            CUT
Ian Woosnam           CUT
Vijay Singh           CUT
Angel Cabrera         CUT
Jose Maria Olazabal   CUT

[87 rows x 1 columns]

In [10]:
merged_df = pd.concat([df1, df2, df3, df4, df5, df6, leaderboard], axis=1, sort=False)

In [11]:
merged_df.isnull().sum()

avg_driv_dist    23
driv_acc%        23
gir%             23
scrambling%      23
sandsaves        23
putting_avg      23
score             1
dtype: int64

In [12]:
merged_df[pd.isnull(merged_df).any(axis=1)]

,avg_driv_dist,driv_acc%,gir%,scrambling%,sandsaves,putting_avg,score
Thorbjørn Olesen,300.4,71.43,72.22,60.0,75.0,1.865,NaN
Thorbjrn Olesen,NaN,NaN,NaN,NaN,NaN,NaN,-5
Kevin OConnell,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Mike Weir,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Danny Willett,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Sergio Garcia,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Sandy Lyle,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Stewart Cink,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Justin Rose,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Adam Long,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Brandt Snedeker,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Fred Couples,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Charl Schwartzel,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Shugo Imahira,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Shane Lowry,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Larry Mize,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Matt Wallace,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Jovan Rebula,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Michael Kim,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Paul Casey,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Ian Woosnam,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Vijay Singh,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Angel Cabrera,NaN,NaN,NaN,NaN,NaN,NaN,CUT
Jose Maria Olazabal,NaN,NaN,NaN,NaN,NaN,NaN,CUT

In [13]:
merged_df = merged_df[~pd.isnull(merged_df).any(axis=1)]
merged_df['year'] = '2019'
merged_df

,avg_driv_dist,driv_acc%,gir%,scrambling%,sandsaves,putting_avg,score,year
Tony Finau,316.3,67.86,66.67,79.17,63.64,1.771,-11,2019
Rory McIlroy,314.4,58.93,62.50,40.74,25.00,1.689,-5,2019
Gary Woodland,313.6,55.36,62.50,51.85,20.00,1.822,-3,2019
Brooks Koepka,313.6,69.64,73.61,68.42,100.00,1.792,-12,2019
Justin Thomas,312.3,73.21,76.39,70.59,50.00,1.818,-8,2019
...,...,...,...,...,...,...,...,...
Zach Johnson,288.1,73.21,56.94,51.61,60.00,1.805,+5,2019
Andrew Landry,287.6,80.36,65.28,60.00,66.67,1.766,E,2019
Kyle Stanley,286.6,69.64,66.67,62.50,50.00,1.813,-5,2019
Webb Simpson,283.1,83.93,68.06,78.26,50.00,1.735,-11,2019
Bernhard Langer,272.6,76.79,63.89,42.31,50.00,1.739,+8,2019

In [14]:
merged_df.to_csv('2019.csv')